"""Domain models for strategy signals and signal idempotency."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class Direction(str, Enum):
    LONG = "long"
    SHORT = "short"


class SignalRejectionReason(str, Enum):
    """Machine-readable rejection reason codes."""

    # Strategy-level rejections
    WRONG_REGIME = "wrong_regime"
    WRONG_SYMBOL = "wrong_symbol"
    WRONG_TIMEFRAME = "wrong_timeframe"
    INSUFFICIENT_SCORE = "insufficient_score"
    RANGE_OR_REVERSION_CONFIRMATION_FAILED = "range_or_reversion_confirmation_failed"
    ENTRY_CONDITIONS_NOT_MET = "entry_conditions_not_met"

    # Freshness / liquidity rejections
    CANDLE_STALE = "candle_stale"
    ORDER_BOOK_STALE = "order_book_stale"
    SPREAD_TOO_WIDE = "spread_too_wide"
    INSUFFICIENT_DEPTH = "insufficient_depth"
    ESTIMATED_SLIPPAGE_TOO_HIGH = "estimated_slippage_too_high"
    DATA_CONTINUITY_BROKEN = "data_continuity_broken"
    EXCHANGE_DISCONNECTED = "exchange_disconnected"

    # Risk rejections
    MAX_OPEN_POSITIONS_REACHED = "max_open_positions_reached"
    MAX_POSITIONS_PER_SYMBOL_REACHED = "max_positions_per_symbol_reached"
    MAX_EXPOSURE_PER_SYMBOL_REACHED = "max_exposure_per_symbol_reached"
    MAX_TOTAL_EXPOSURE_REACHED = "max_total_exposure_reached"
    MAX_DAILY_LOSS_REACHED = "max_daily_loss_reached"
    MAX_DRAWDOWN_REACHED = "max_drawdown_reached"
    ENTRY_COOLDOWN_ACTIVE = "entry_cooldown_active"
    KILL_SWITCH_ENGAGED = "kill_switch_engaged"
    POSITION_SIZE_ZERO = "position_size_zero"

    # Idempotency
    DUPLICATE_SIGNAL = "duplicate_signal"

    # Technical
    INSUFFICIENT_HISTORY = "insufficient_history"
    RECONCILIATION_FAILED = "reconciliation_failed"


@dataclass(frozen=True, slots=True)
class SignalId:
    """Deterministic signal identifier.

    Format: strategy_id:strategy_version:symbol:timeframe:candle_timestamp:direction
    Example: bnb_range_reversion:v1:BNB-USDT:1h:2026-07-13T10:00:00Z:long
    """

    strategy_id: str
    strategy_version: str
    symbol: str
    timeframe: str
    candle_timestamp: datetime
    direction: Direction

    def __str__(self) -> str:
        ts = self.candle_timestamp.strftime("%Y-%m-%dT%H:%M:%SZ")
        return f"{self.strategy_id}:{self.strategy_version}:{self.symbol}:{self.timeframe}:{ts}:{self.direction.value}"

    @classmethod
    def parse(cls, signal_id_str: str) -> "SignalId":
        """Parse a signal ID string back into a SignalId."""
        parts = signal_id_str.split(":")
        # The timestamp contains colons, so we have more than 6 parts.
        # Fixed fields: strategy_id(0), version(1), symbol(2), timeframe(3)
        # Timestamp: parts 4,5,6 (YYYY-MM-DDTHH, MM, SSZ)
        # Direction: last part
        if len(parts) < 7:
            raise ValueError(f"Invalid signal ID format: {signal_id_str}")
        ts = f"{parts[4]}:{parts[5]}:{parts[6]}"
        direction = parts[7] if len(parts) > 7 else parts[-1]
        return cls(
            strategy_id=parts[0],
            strategy_version=parts[1],
            symbol=parts[2],
            timeframe=parts[3],
            candle_timestamp=datetime.strptime(ts, "%Y-%m-%dT%H:%M:%SZ"),
            direction=Direction(direction),
        )


@dataclass(frozen=True, slots=True)
class StrategySignal:
    """A signal generated by a strategy for a specific candle."""

    signal_id: SignalId
    strategy_id: str
    strategy_version: str
    symbol: str
    timeframe: str
    candle_timestamp: datetime
    direction: Direction
    regime: str
    score: float  # strategy confidence score 0-100
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    metadata: dict = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass(frozen=True, slots=True)
class SignalRejection:
    """A structured rejection when a strategy cannot generate a valid signal."""

    strategy_id: str
    strategy_version: str
    symbol: str
    timeframe: str
    candle_timestamp: datetime
    direction: Direction
    reason: SignalRejectionReason
    detail: str = ""
    created_at: datetime = field(default_factory=datetime.utcnow)

    @property
    def signal_id(self) -> str:
        """Generate the same deterministic ID for tracking purposes."""
        sid = SignalId(
            strategy_id=self.strategy_id,
            strategy_version=self.strategy_version,
            symbol=self.symbol,
            timeframe=self.timeframe,
            candle_timestamp=self.candle_timestamp,
            direction=self.direction,
        )
        return str(sid)
